package fr.gphy.piotrgui.j2eged.model;
// Generated 11 oct. 2013 16:39:56 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private Integer idDoc;
     private Document documentByDocPost;
     private Document documentByDocAnt;
     private Set<Document> documentsForDocAnt = new HashSet<Document>(0);
     private Set<Document> documentsForDocPost = new HashSet<Document>(0);
     private Set<Version> versions = new HashSet<Version>(0);
     private Set<PhysicalDocument> physicalDocuments = new HashSet<PhysicalDocument>(0);

    public Document() {
    }

    public Document(Document documentByDocPost, Document documentByDocAnt, Set<Document> documentsForDocAnt, Set<Document> documentsForDocPost, Set<Version> versions, Set<PhysicalDocument> physicalDocuments) {
       this.documentByDocPost = documentByDocPost;
       this.documentByDocAnt = documentByDocAnt;
       this.documentsForDocAnt = documentsForDocAnt;
       this.documentsForDocPost = documentsForDocPost;
       this.versions = versions;
       this.physicalDocuments = physicalDocuments;
    }
   
    public Integer getIdDoc() {
        return this.idDoc;
    }
    
    public void setIdDoc(Integer idDoc) {
        this.idDoc = idDoc;
    }
    public Document getDocumentByDocPost() {
        return this.documentByDocPost;
    }
    
    public void setDocumentByDocPost(Document documentByDocPost) {
        this.documentByDocPost = documentByDocPost;
    }
    public Document getDocumentByDocAnt() {
        return this.documentByDocAnt;
    }
    
    public void setDocumentByDocAnt(Document documentByDocAnt) {
        this.documentByDocAnt = documentByDocAnt;
    }
    public Set<Document> getDocumentsForDocAnt() {
        return this.documentsForDocAnt;
    }
    
    public void setDocumentsForDocAnt(Set<Document> documentsForDocAnt) {
        this.documentsForDocAnt = documentsForDocAnt;
    }
    public Set<Document> getDocumentsForDocPost() {
        return this.documentsForDocPost;
    }
    
    public void setDocumentsForDocPost(Set<Document> documentsForDocPost) {
        this.documentsForDocPost = documentsForDocPost;
    }
    public Set<Version> getVersions() {
        return this.versions;
    }
    
    public void setVersions(Set<Version> versions) {
        this.versions = versions;
    }
    public Set<PhysicalDocument> getPhysicalDocuments() {
        return this.physicalDocuments;
    }
    
    public void setPhysicalDocuments(Set<PhysicalDocument> physicalDocuments) {
        this.physicalDocuments = physicalDocuments;
    }




}


