package fr.gphy.piotrgui.j2eged.model;
// Generated 2 oct. 2013 16:50:55 by Hibernate Tools 3.2.1.GA

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private Integer idDoc;
     private Document documentByDocPost;
     private PhysicalDocument physicalDocument;
     private Document documentByDocAnt;

    public Document() {
    }

	
    public Document(PhysicalDocument physicalDocument) {
        this.physicalDocument = physicalDocument;
    }
    public Document(Document documentByDocPost, PhysicalDocument physicalDocument, Document documentByDocAnt) {
       this.documentByDocPost = documentByDocPost;
       this.physicalDocument = physicalDocument;
       this.documentByDocAnt = documentByDocAnt;
    }
   
    public Integer getIdDoc() {
        return this.idDoc;
    }
    
    public void setIdDoc(Integer idDoc) {
        this.idDoc = idDoc;
    }
    public Document getDocumentByDocPost() {
        return this.documentByDocPost;
    }
    
    public void setDocumentByDocPost(Document documentByDocPost) {
        this.documentByDocPost = documentByDocPost;
    }
    public PhysicalDocument getPhysicalDocument() {
        return this.physicalDocument;
    }
    
    public void setPhysicalDocument(PhysicalDocument physicalDocument) {
        this.physicalDocument = physicalDocument;
    }
    public Document getDocumentByDocAnt() {
        return this.documentByDocAnt;
    }
    
    public void setDocumentByDocAnt(Document documentByDocAnt) {
        this.documentByDocAnt = documentByDocAnt;
    }

}


