package fr.gphy.piotrgui.j2eged.model;
// Generated 2 oct. 2013 16:50:55 by Hibernate Tools 3.2.1.GA


import java.util.Set;

/**
 * Folder generated by hbm2java
 */
public class Folder  implements java.io.Serializable {

    private Integer idFolder;
    private Folder folder;
    private String name;

    public Folder() {}

    public Folder(Folder folder, String name) {
       this.folder = folder;
       this.name = name;
    }
   
    public Integer getIdFolder() {
        return this.idFolder;
    }
    
    public void setIdFolder(Integer idFolder) {
        this.idFolder = idFolder;
    }
    
    public Folder getFolder() {
        return this.folder;
    }
    
    public void setFolder(Folder folder) {
        this.folder = folder;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

}


