package fr.gphy.piotrgui.j2eged.model;
// Generated 11 oct. 2013 16:39:56 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Metadata generated by hbm2java
 */
public class Metadata  implements java.io.Serializable {


     private Integer idMeta;
     private int version;
     private Type type;
     private User user;
     private Folder folder;
     private int size;
     private Date dateCreation;
     private String name;
     private Set<Version> versions = new HashSet<Version>(0);

    public Metadata() {
    }

	
    public Metadata(Type type, User user, Folder folder, int size, Date dateCreation, String name) {
        this.type = type;
        this.user = user;
        this.folder = folder;
        this.size = size;
        this.dateCreation = dateCreation;
        this.name = name;
    }
    public Metadata(Type type, User user, Folder folder, int size, Date dateCreation, String name, Set<Version> versions) {
       this.type = type;
       this.user = user;
       this.folder = folder;
       this.size = size;
       this.dateCreation = dateCreation;
       this.name = name;
       this.versions = versions;
    }
   
    public Integer getIdMeta() {
        return this.idMeta;
    }
    
    public void setIdMeta(Integer idMeta) {
        this.idMeta = idMeta;
    }
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Folder getFolder() {
        return this.folder;
    }
    
    public void setFolder(Folder folder) {
        this.folder = folder;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Version> getVersions() {
        return this.versions;
    }
    
    public void setVersions(Set<Version> versions) {
        this.versions = versions;
    }




}


