package fr.gphy.piotrgui.j2eged.model;
// Generated 7 oct. 2013 11:33:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer idType;
     private String mimeType;
     private String fileExtension;
     private Set<Metadata> metadatas = new HashSet<Metadata>(0);

    public Type() {
    }

	
    public Type(String mimeType, String fileExtension) {
        this.mimeType = mimeType;
        this.fileExtension = fileExtension;
    }
    public Type(String mimeType, String fileExtension, Set<Metadata> metadatas) {
       this.mimeType = mimeType;
       this.fileExtension = fileExtension;
       this.metadatas = metadatas;
    }
   
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }
    public String getFileExtension() {
        return this.fileExtension;
    }
    
    public void setFileExtension(String fileExtension) {
        this.fileExtension = fileExtension;
    }
    public Set<Metadata> getMetadatas() {
        return this.metadatas;
    }
    
    public void setMetadatas(Set<Metadata> metadatas) {
        this.metadatas = metadatas;
    }




}


