package fr.gphy.piotrgui.j2eged.model;
// Generated 2 oct. 2013 16:50:55 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private Role role;
     private String login;
     private String password;
     private Set<Version> versions = new HashSet<Version>(0);
     private Set<Metadata> metadatas = new HashSet<Metadata>(0);

    public User() {
    }

	
    public User(Role role, String login, String password) {
        this.role = role;
        this.login = login;
        this.password = password;
    }
    public User(Role role, String login, String password, Set<Version> versions, Set<Metadata> metadatas) {
       this.role = role;
       this.login = login;
       this.password = password;
       this.versions = versions;
       this.metadatas = metadatas;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<Version> getVersions() {
        return this.versions;
    }
    
    public void setVersions(Set<Version> versions) {
        this.versions = versions;
    }
    public Set<Metadata> getMetadatas() {
        return this.metadatas;
    }
    
    public void setMetadatas(Set<Metadata> metadatas) {
        this.metadatas = metadatas;
    }




}


